spring:
  profiles:
    default: dev

  datasource:
    url: jdbc:mysql://localhost:3306/savedb?useSSL=false&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: takim
    password: takim
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
