spring:
  profiles:
    default: dev
  properties:
    hibernate:
      default_batch_fetch_size: 100
  session:
    store-type: jdbc
    jdbc.initialize-schema: always

  datasource:
    url: jdbc:mysql://savedb.ciauqxcnc0ry.ap-northeast-2.rds.amazonaws.com/newsavedb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: adminadmin
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
